function options = nmpc_fmincon_options(cfg)
%NMPC_FMINCON_OPTIONS Build fmincon options from the step-2 config.

if exist('fmincon', 'file') ~= 2
    error('nmpc_fmincon_options:MissingSolver', ...
          'fmincon is required for step-2 NMPC. Install Optimization Toolbox or choose another solver.');
end

solver = cfg.solver;
options = optimoptions('fmincon', ...
    'Algorithm', solver.algorithm, ...
    'Display', solver.display, ...
    'MaxIterations', solver.maxIterations, ...
    'MaxFunctionEvaluations', solver.maxFunctionEvaluations, ...
    'ConstraintTolerance', solver.constraintTolerance, ...
    'OptimalityTolerance', solver.optimalityTolerance, ...
    'StepTolerance', solver.stepTolerance);
end
