function run_targeted_reference_tests()
%RUN_TARGETED_REFERENCE_TESTS Check finite, analytic targeted references.

projectRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(projectRoot, 'src', 'common'));
addpath(fullfile(projectRoot, 'src', 'plant'));
addpath(fullfile(projectRoot, 'src', 'controllers', 'common'));
addpath(fullfile(projectRoot, 'configs'));
plantCfg = step1_plant_config();
nmpcCfg = step2_nmpc_config();
sampleTime = 0.01;
sampleCount = 1001;
cases = { ...
    'circle', struct('radius', 0.5, 'targetPeakSpeed', 1.2); ...
    'lemniscate', struct('amplitude', [0.7; 0.4], ...
        'targetPeakSpeed', 1.4); ...
    'vertical_circle', struct('radius', 0.4, ...
        'targetPeakSpeed', 1.0); ...
    'spatial_helix', struct('radius', 0.5, ...
        'verticalAmplitude', 0.25, 'verticalRatio', 0.5, ...
        'targetPeakSpeed', 1.5); ...
    'smooth_waypoints', struct('waypoints', ...
        [0, 0.8, 0.2; 0, 0.3, -0.5; 1.0, 1.2, 0.9], ...
        'segmentDurations', [1.5, 1.7])};

for index = 1:size(cases, 1)
    [reference, time, feedforward, flatness] = ...
        quad_targeted_reference_trajectory( ...
        cases{index, 1}, sampleTime, sampleCount, cases{index, 2});
    assert(isequal(size(reference), [12, sampleCount]));
    assert(isequal(size(time), [1, sampleCount]));
    assert(all(isfinite(reference), 'all'));
    assert(isequal(size(feedforward), [4, sampleCount]));
    assert(all(isfinite(feedforward), 'all'));
    desiredBodyZ = flatness.forceVector ./ ...
        vecnorm(flatness.forceVector, 2, 1);
    actualBodyZ = squeeze(flatness.rotation(:, 3, :));
    alignmentError = vecnorm(desiredBodyZ - actualBodyZ, 2, 1);
    assert(max(alignmentError) < 1e-10, ...
        'Thrust-direction consistency failed for %s.', cases{index, 1});
    assert(all(feedforward(1, :) >= plantCfg.nominal.inputLimits.T(1)));
    assert(all(feedforward(1, :) <= plantCfg.nominal.inputLimits.T(2)));
    feasibility = quad_reference_feasibility_metrics(reference, ...
        feedforward, flatness, sampleTime, plantCfg.nominal, nmpcCfg);
    assert(feasibility.finite);
    assert(feasibility.peakInputFraction <= 1.0 + 1e-10, ...
        'Feedforward input bound failed for %s.', cases{index, 1});
    assert(feasibility.dynamicResidualP95 < 0.25, ...
        'Dynamic consistency failed for %s.', cases{index, 1});
    numericalVelocity = diff(reference(1:3, :), 1, 2) ./ sampleTime;
    analyticVelocity = 0.5 .* (reference(7:9, 1:end-1) + ...
        reference(7:9, 2:end));
    active = vecnorm(analyticVelocity, 2, 1) > 1e-4;
    relativeError = vecnorm(numericalVelocity(:, active) - ...
        analyticVelocity(:, active), 2, 1) ./ ...
        max(vecnorm(analyticVelocity(:, active), 2, 1), 1e-6);
    assert(percentile_linear(relativeError, 95) < 0.02, ...
        'Velocity consistency failed for %s.', cases{index, 1});
    if ~strcmp(cases{index, 1}, 'smooth_waypoints')
        assert(max(abs(reference(4:5, :)), [], 'all') > deg2rad(1), ...
            'Dynamic attitude completion failed for %s.', cases{index, 1});
    end
end
fprintf('Targeted reference tests passed: %d families.\n', size(cases, 1));
end

function value = percentile_linear(values, percentage)
values = sort(values(isfinite(values)));
rankValue = 1 + (numel(values) - 1) * percentage / 100;
lowerIndex = floor(rankValue);
upperIndex = ceil(rankValue);
weight = rankValue - lowerIndex;
value = (1 - weight) * values(lowerIndex) + weight * values(upperIndex);
end
