function targeted_sac_validate_resume_config(savedCfg, activeCfg)
%TARGETED_SAC_VALIDATE_RESUME_CONFIG Reject incompatible SAC checkpoints.

if ~isfield(savedCfg, 'observation') || ...
        ~isfield(savedCfg.observation, 'featureVersion') || ...
        ~isfield(savedCfg.observation, 'dimension')
    error('targeted_sac_validate_resume_config:MissingMetadata', ...
        'Resume source lacks observation contract metadata.');
end
if ~strcmp(savedCfg.observation.featureVersion, ...
        activeCfg.observation.featureVersion) || ...
        savedCfg.observation.dimension ~= activeCfg.observation.dimension
    error('targeted_sac_validate_resume_config:IncompatibleObservation', ...
        ['Resume checkpoint observation contract is incompatible. A legacy ' ...
        '31D agent/replay cannot be resumed into causal_feature_v2.']);
end
end
