function [observation, rawFeature] = ...
        targeted_sac_make_causal_observation(stateHistory, inputHistory, ...
        referenceLookahead, predictionResidual, cfg)
%TARGETED_SAC_MAKE_CAUSAL_OBSERVATION Normalize causal feature v2 for SAC.

assert(strcmp(cfg.observation.featureVersion, 'causal_feature_v2'), ...
    'The active targeted SAC feature contract must be causal_feature_v2.');
rawFeature = targeted_surrogate_build_feature(stateHistory, inputHistory, ...
    referenceLookahead, predictionResidual);

stateScale = cfg.observation.stateScale(:);
referenceScale = cfg.observation.referenceScale(:);
inputCenter = cfg.observation.inputCenter(:);
inputScale = cfg.observation.inputScale(:);
residualScale = cfg.observation.residualScale(:);
assert(numel(stateScale) == 12 && numel(referenceScale) == 12 && ...
    numel(inputCenter) == 4 && numel(inputScale) == 4 && ...
    numel(residualScale) == 12 && all(stateScale > 0) && ...
    all(referenceScale > 0) && all(inputScale > 0) && ...
    all(residualScale > 0), 'Invalid causal observation scales.');

normalizedState = stateHistory ./ stateScale;
normalizedInput = (inputHistory - inputCenter) ./ inputScale;
normalizedReference = referenceLookahead ./ referenceScale;
normalizedResidual = predictionResidual ./ residualScale;
observation = [normalizedState(:); normalizedInput(:); ...
    normalizedReference(:); normalizedResidual(:)];
assert(numel(observation) == cfg.observation.dimension && ...
    numel(observation) == 328 && all(isfinite(observation)), ...
    'Normalized causal observation must contain 328 finite values.');
observation = min(max(observation, -cfg.observation.clip), ...
    cfg.observation.clip);
end
