function feature = confidence_build_feature(normalizedClipped, ...
        normalizedRaw, rawControl, predictionResidual, plant, featureSet)
%CONFIDENCE_BUILD_FEATURE Build runtime-only confidence features.

if ~isequal(size(normalizedClipped), [208, 1]) || ...
        ~isequal(size(normalizedRaw), [208, 1]) || ...
        ~isequal(size(rawControl), [4, 1]) || ...
        ~isequal(size(predictionResidual), [12, 1])
    error('confidence_build_feature:BadInputSize', ...
        'Confidence feature inputs have incompatible dimensions.');
end
inputLower = [plant.inputLimits.T(1); plant.inputLimits.tau(:, 1)];
inputUpper = [plant.inputLimits.T(2); plant.inputLimits.tau(:, 2)];
inputMidpoint = 0.5 * (inputLower + inputUpper);
inputHalfRange = 0.5 * (inputUpper - inputLower);
normalizedControl = (rawControl - inputMidpoint) ./ inputHalfRange;

if strcmp(featureSet, 'F1')
    feature = normalizedClipped;
elseif strcmp(featureSet, 'F2')
    feature = [normalizedClipped; normalizedControl];
elseif strcmp(featureSet, 'F3')
    summaries = [max(abs(normalizedRaw)); ...
        mean(abs(normalizedRaw) > 3); ...
        norm(predictionResidual(1:3)); ...
        norm(predictionResidual(4:6)); ...
        norm(predictionResidual(7:9)); ...
        norm(predictionResidual(10:12)); ...
        min(1 - abs(normalizedControl))];
    feature = [normalizedClipped; normalizedControl; summaries];
else
    error('confidence_build_feature:BadFeatureSet', ...
        'Unknown confidence feature set: %s', featureSet);
end
if any(~isfinite(feature))
    error('confidence_build_feature:InvalidFeature', ...
        'Confidence feature must be finite.');
end
end
